name: .NET CD on commit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACRNAME: 'openhackx6e34ru4acr'
      BASEIMAGETAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
    
      - name: Acr Build
        run: |
          cd web
          az acr build --image "devopsoh/api-poi:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackx6e34ru4poi
          slot-name: staging
          images: 'openhackx6e34ru4acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}'